<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "dog".
 *
 * @property integer $id
 * @property integer $member_id
 * @property string $name
 * @property string $pedigreeName
 * @property string $breeder
 * @property string $dob
 * @property integer $sex
 * @property string $link
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\Member $member
 * @property string $aliasModel
 */
abstract class Dog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dog';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['member_id', 'name', 'pedigreeName'], 'required'],
            [['member_id', 'sex'], 'integer'],
            [['name', 'pedigreeName', 'breeder', 'link'], 'string'],
            [['dob'], 'safe'],
            [['member_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Member::className(), 'targetAttribute' => ['member_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'member_id' => 'Member ID',
            'name' => 'Name',
            'pedigreeName' => 'Pedigree Name',
            'breeder' => 'Breeder',
            'dob' => 'Dob',
            'sex' => 'Sex',
            'link' => 'Link',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMember()
    {
        return $this->hasOne(\app\models\Member::className(), ['id' => 'member_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\DogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\DogQuery(get_called_class());
    }


}
