<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "entry".
 *
 * @property integer $id
 * @property integer $eventclass_id
 * @property array $details
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\Eventclass $eventclass
 * @property string $aliasModel
 */
abstract class Entry extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'entry';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['eventclass_id'], 'required'],
            [['eventclass_id'], 'integer'],
            [['details'], 'safe'],
            [['eventclass_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\EventClass::className(), 'targetAttribute' => ['eventclass_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'eventclass_id' => 'Eventclass ID',
            'details' => 'Details',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventclass()
    {
        return $this->hasOne(\app\models\EventClass::className(), ['id' => 'eventclass_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\EntryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\EntryQuery(get_called_class());
    }


}
