<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "membertype".
 *
 * @property integer $id
 * @property string $type
 * @property string $description
 * @property string $aliasModel
 */
abstract class Membertype extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'membertype';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type'], 'required'],
            [['type'], 'string', 'max' => 20],
            [['description'], 'string', 'max' => 80]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'description' => 'Description',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\MembertypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\MembertypeQuery(get_called_class());
    }


}
