<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "transaction".
 *
 * @property integer $id
 * @property integer $member_id
 * @property string $date
 * @property integer $type
 * @property string $description
 * @property string $amount
 * @property string $payment_method
 * @property string $reference
 * @property string $account
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\Member $member
 * @property string $aliasModel
 */
abstract class Transaction extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'transaction';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['member_id', 'date'], 'required'],
            [['member_id', 'type'], 'integer'],
            [['date'], 'safe'],
            [['amount'], 'number'],
            [['description'], 'string', 'max' => 140],
            [['payment_method'], 'string', 'max' => 40],
            [['reference', 'account'], 'string', 'max' => 20],
            [['member_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Member::className(), 'targetAttribute' => ['member_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'member_id' => 'Member ID',
            'date' => 'Date',
            'type' => 'Type',
            'description' => 'Description',
            'amount' => 'Amount',
            'payment_method' => 'Payment Method',
            'reference' => 'Reference',
            'account' => 'Account',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMember()
    {
        return $this->hasOne(\app\models\Member::className(), ['id' => 'member_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\TransactionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\TransactionQuery(get_called_class());
    }


}
