<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Dog $model
* @var yii\widgets\ActiveForm $form
* @var string $relAttributes relation fields names for disabling 
*/

?>

<div class="dog-form">

    <?php $form = ActiveForm::begin([
        'id' => 'Dog',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'member_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Member::find()->all(), 'id', 'firstname', 'lastname'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['member_id'])),
                ]
            ); ?>
            <?= $form->field($model, 'name')->textInput() ?>
            <?= $form->field($model, 'pedigreeName')->textInput() ?>
            <?= $form->field($model, 'breeder')->textInput() ?>
            <?= $form->field($model, 'dob')->widget(\yii\jui\DatePicker::class, ['dateFormat'=>'yyyy-MM-dd',]) ?>
            <?= $form->field($model, 'sex')->dropDownList(['Male','Female']) ?>
            <?= $form->field($model, 'link')->textarea(['rows' => 2]) ?>
            <?= $form->field($model, 'created_at',['inputOptions' => ['value' => Yii::$app->formatter->asDatetime($model->created_at,'yyyy-MM-dd hh:mm'),'readonly'=>true]]) ?>
            <?= $form->field($model, 'updated_at',['inputOptions' => ['value' => Yii::$app->formatter->asDatetime($model->updated_at,'yyyy-MM-dd hh:mm'),'readonly'=>true]]) ?>
            <?= $form->field($model, 'created_by')->textInput(['readonly' => true,]) ?>
            <?= $form->field($model, 'updated_by')->textInput(['readonly' => true,]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [ [
                    'label'   => Yii::t('cruds', StringHelper::basename('app\models\Dog')),
                    'content' => $this->blocks['main'],
                    'active'  => true,
                    ], ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

